name: Python package

on:
  release:
    types: ['published']


jobs:

  pypi_build:
    name: Build pypi package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          pip install -r requirements.txt
          pip install -e .
      - name: Build pypi package
        run: |
          python -m build
      - name: Upload build package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  deploy_pypi:
    name: Publish to pypi
    needs: pypi_build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/keras-batchflow
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}